name: Token issue debugging

on:
  pull_request:
    branches: [ main ]

jobs:
  debugging:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Write with GH API
      run: |
        curl -LsX POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -d '{"body":"Hello :)"}' "${{ github.event.pull_request.comments_url }}"
        echo $?
    - name: Try with github-script action
      uses: actions/github-script@v7
      with:
        script: |
            github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'ðŸ‘‹ Thanks for reporting!'
            })